/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

/**
 *
 * @author gollu
 */
public class NewJPanel extends javax.swing.JPanel
{

    /**
     * Creates new form NewJPanel
     */
    public NewJPanel()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        pnRegistro = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        pnRegistro1 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        pnProv = new javax.swing.JPanel();
        lbProveedor = new javax.swing.JLabel();
        lbPrv1 = new javax.swing.JLabel();
        lbPrv2 = new javax.swing.JLabel();
        lbPrv3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnProd = new javax.swing.JPanel();
        lbProducto = new javax.swing.JLabel();
        lbP1 = new javax.swing.JLabel();
        lbP2 = new javax.swing.JLabel();
        lbP3 = new javax.swing.JLabel();
        lbP4 = new javax.swing.JLabel();
        lbP5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pnSuc = new javax.swing.JPanel();
        lbSuc = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbS1 = new javax.swing.JLabel();
        lbS2 = new javax.swing.JLabel();
        lbS3 = new javax.swing.JLabel();
        lbS4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnRegistro.setBackground(new java.awt.Color(255, 255, 255));
        pnRegistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel31.setText("e");
        jLabel31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnRegistro.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 160, 32));

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("e");
        jLabel32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnRegistro.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 80, 32));

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel33.setText("e");
        jLabel33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnRegistro.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 160, 32));

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel34.setText("e");
        jLabel34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnRegistro.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 160, 32));

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("e");
        jLabel35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnRegistro.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 160, 32));

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel30.setText("e");
        jLabel30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnRegistro.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 32));

        add(pnRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 880, 32));

        pnRegistro1.setBackground(new java.awt.Color(255, 255, 255));
        pnRegistro1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel21.setText("e");
        jLabel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnRegistro1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 200, 32));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel22.setText("e");
        jLabel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnRegistro1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 200, 32));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel23.setText("e");
        jLabel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnRegistro1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 200, 32));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("e");
        jLabel24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnRegistro1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 120, 32));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("e");
        jLabel25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnRegistro1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, 80, 32));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("e");
        jLabel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnRegistro1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 32));

        add(pnRegistro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 880, 32));

        pnProv.setBackground(new java.awt.Color(255, 255, 255));
        pnProv.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnProv.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbProveedor.setBackground(new java.awt.Color(66, 141, 141));
        lbProveedor.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbProveedor.setForeground(new java.awt.Color(255, 255, 255));
        lbProveedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbProveedor.setText("Proveedor Texto");
        lbProveedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbProveedor.setOpaque(true);
        pnProv.add(lbProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 290, 30));

        lbPrv1.setBackground(new java.awt.Color(175, 207, 207));
        lbPrv1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbPrv1.setText("  Clave:");
        lbPrv1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbPrv1.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                lbPrv1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                lbPrv1MouseExited(evt);
            }
        });
        pnProv.add(lbPrv1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 290, 45));

        lbPrv2.setBackground(new java.awt.Color(175, 207, 207));
        lbPrv2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbPrv2.setText("  Direcccion:");
        lbPrv2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbPrv2.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                lbPrv2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                lbPrv2MouseExited(evt);
            }
        });
        pnProv.add(lbPrv2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 290, 45));

        lbPrv3.setBackground(new java.awt.Color(175, 207, 207));
        lbPrv3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbPrv3.setText("  Correo:");
        lbPrv3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbPrv3.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                lbPrv3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                lbPrv3MouseExited(evt);
            }
        });
        pnProv.add(lbPrv3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 290, 45));

        jLabel2.setBackground(new java.awt.Color(66, 141, 141));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/repartidor (1).png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel2.setOpaque(true);
        pnProv.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 80));

        add(pnProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 220, 290, -1));

        pnProd.setBackground(new java.awt.Color(255, 255, 255));
        pnProd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnProd.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbProducto.setBackground(new java.awt.Color(66, 141, 141));
        lbProducto.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbProducto.setForeground(new java.awt.Color(255, 255, 255));
        lbProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbProducto.setText("Producto Texto");
        lbProducto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbProducto.setOpaque(true);
        pnProd.add(lbProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 290, 30));

        lbP1.setBackground(new java.awt.Color(175, 207, 207));
        lbP1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbP1.setText("  Clave: ");
        lbP1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbP1.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                lbP1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                lbP1MouseExited(evt);
            }
        });
        pnProd.add(lbP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 290, 30));

        lbP2.setBackground(new java.awt.Color(175, 207, 207));
        lbP2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbP2.setText("  Sucursal:");
        lbP2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbP2.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                lbP2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                lbP2MouseExited(evt);
            }
        });
        pnProd.add(lbP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 290, 30));

        lbP3.setBackground(new java.awt.Color(175, 207, 207));
        lbP3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbP3.setText("  Proveedor:");
        lbP3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbP3.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                lbP3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                lbP3MouseExited(evt);
            }
        });
        pnProd.add(lbP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 290, 30));

        lbP4.setBackground(new java.awt.Color(175, 207, 207));
        lbP4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbP4.setText("  Precio:");
        lbP4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbP4.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                lbP4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                lbP4MouseExited(evt);
            }
        });
        pnProd.add(lbP4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 290, 30));

        lbP5.setBackground(new java.awt.Color(175, 207, 207));
        lbP5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbP5.setText("  Existencia:");
        lbP5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbP5.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                lbP5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                lbP5MouseExited(evt);
            }
        });
        pnProd.add(lbP5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 290, 30));

        jLabel3.setBackground(new java.awt.Color(66, 141, 141));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/farmacias.png"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel3.setOpaque(true);
        pnProd.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 80));

        add(pnProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 490, 290, -1));

        pnSuc.setBackground(new java.awt.Color(255, 255, 255));
        pnSuc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnSuc.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbSuc.setBackground(new java.awt.Color(66, 141, 141));
        lbSuc.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbSuc.setForeground(new java.awt.Color(255, 255, 255));
        lbSuc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSuc.setText("Sucursal");
        lbSuc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbSuc.setOpaque(true);
        pnSuc.add(lbSuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 290, 30));

        jLabel4.setBackground(new java.awt.Color(66, 141, 141));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/farmacia.png"))); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel4.setOpaque(true);
        pnSuc.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 80));

        lbS1.setBackground(new java.awt.Color(175, 207, 207));
        lbS1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbS1.setText("  Farmacia: ");
        lbS1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbS1.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                lbS1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                lbS1MouseExited(evt);
            }
        });
        pnSuc.add(lbS1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 290, 40));

        lbS2.setBackground(new java.awt.Color(175, 207, 207));
        lbS2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbS2.setText("  Clave:");
        lbS2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbS2.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                lbS2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                lbS2MouseExited(evt);
            }
        });
        pnSuc.add(lbS2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 290, 40));

        lbS3.setBackground(new java.awt.Color(175, 207, 207));
        lbS3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbS3.setText("  Estado:");
        lbS3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbS3.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                lbS3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                lbS3MouseExited(evt);
            }
        });
        pnSuc.add(lbS3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 290, 40));

        lbS4.setBackground(new java.awt.Color(175, 207, 207));
        lbS4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbS4.setText("  Telefono:");
        lbS4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbS4.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                lbS4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                lbS4MouseExited(evt);
            }
        });
        pnSuc.add(lbS4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 290, 40));

        add(pnSuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 290, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void lbP1MouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lbP1MouseEntered
    {//GEN-HEADEREND:event_lbP1MouseEntered
        lbP1.setOpaque(true);
    }//GEN-LAST:event_lbP1MouseEntered

    private void lbP1MouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lbP1MouseExited
    {//GEN-HEADEREND:event_lbP1MouseExited
        lbP1.setOpaque(false);
    }//GEN-LAST:event_lbP1MouseExited

    private void lbPrv1MouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lbPrv1MouseEntered
    {//GEN-HEADEREND:event_lbPrv1MouseEntered
        lbPrv1.setOpaque(true);
    }//GEN-LAST:event_lbPrv1MouseEntered

    private void lbPrv1MouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lbPrv1MouseExited
    {//GEN-HEADEREND:event_lbPrv1MouseExited
         lbPrv1.setOpaque(false);
    }//GEN-LAST:event_lbPrv1MouseExited

    private void lbPrv2MouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lbPrv2MouseEntered
    {//GEN-HEADEREND:event_lbPrv2MouseEntered
        lbPrv2.setOpaque(true);
    }//GEN-LAST:event_lbPrv2MouseEntered

    private void lbPrv2MouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lbPrv2MouseExited
    {//GEN-HEADEREND:event_lbPrv2MouseExited
        lbPrv2.setOpaque(false);
    }//GEN-LAST:event_lbPrv2MouseExited

    private void lbPrv3MouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lbPrv3MouseEntered
    {//GEN-HEADEREND:event_lbPrv3MouseEntered
        lbPrv3.setOpaque(true);
    }//GEN-LAST:event_lbPrv3MouseEntered

    private void lbPrv3MouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lbPrv3MouseExited
    {//GEN-HEADEREND:event_lbPrv3MouseExited
       lbPrv3.setOpaque(false);
    }//GEN-LAST:event_lbPrv3MouseExited

    private void lbP2MouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lbP2MouseEntered
    {//GEN-HEADEREND:event_lbP2MouseEntered
        lbP2.setOpaque(true);
    }//GEN-LAST:event_lbP2MouseEntered

    private void lbP2MouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lbP2MouseExited
    {//GEN-HEADEREND:event_lbP2MouseExited
      lbP2.setOpaque(false);
    }//GEN-LAST:event_lbP2MouseExited

    private void lbP3MouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lbP3MouseEntered
    {//GEN-HEADEREND:event_lbP3MouseEntered
        lbP3.setOpaque(true);
    }//GEN-LAST:event_lbP3MouseEntered

    private void lbP3MouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lbP3MouseExited
    {//GEN-HEADEREND:event_lbP3MouseExited
        lbP3.setOpaque(false);
    }//GEN-LAST:event_lbP3MouseExited

    private void lbP5MouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lbP5MouseEntered
    {//GEN-HEADEREND:event_lbP5MouseEntered
        lbP5.setOpaque(true);
    }//GEN-LAST:event_lbP5MouseEntered

    private void lbP5MouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lbP5MouseExited
    {//GEN-HEADEREND:event_lbP5MouseExited
         lbP5.setOpaque(false);
    }//GEN-LAST:event_lbP5MouseExited

    private void lbP4MouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lbP4MouseEntered
    {//GEN-HEADEREND:event_lbP4MouseEntered
        lbP4.setOpaque(true);
    }//GEN-LAST:event_lbP4MouseEntered

    private void lbP4MouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lbP4MouseExited
    {//GEN-HEADEREND:event_lbP4MouseExited
        lbP4.setOpaque(false);
    }//GEN-LAST:event_lbP4MouseExited

    private void lbS1MouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lbS1MouseEntered
    {//GEN-HEADEREND:event_lbS1MouseEntered
        lbS1.setOpaque(true);
    }//GEN-LAST:event_lbS1MouseEntered

    private void lbS1MouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lbS1MouseExited
    {//GEN-HEADEREND:event_lbS1MouseExited
       lbS1.setOpaque(false);
    }//GEN-LAST:event_lbS1MouseExited

    private void lbS2MouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lbS2MouseEntered
    {//GEN-HEADEREND:event_lbS2MouseEntered
        lbS2.setOpaque(true);
    }//GEN-LAST:event_lbS2MouseEntered

    private void lbS2MouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lbS2MouseExited
    {//GEN-HEADEREND:event_lbS2MouseExited
        lbS2.setOpaque(false);
    }//GEN-LAST:event_lbS2MouseExited

    private void lbS3MouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lbS3MouseEntered
    {//GEN-HEADEREND:event_lbS3MouseEntered
        lbS3.setOpaque(true);
    }//GEN-LAST:event_lbS3MouseEntered

    private void lbS3MouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lbS3MouseExited
    {//GEN-HEADEREND:event_lbS3MouseExited
        lbS3.setOpaque(false);
    }//GEN-LAST:event_lbS3MouseExited

    private void lbS4MouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lbS4MouseEntered
    {//GEN-HEADEREND:event_lbS4MouseEntered
        lbS4.setOpaque(true);
    }//GEN-LAST:event_lbS4MouseEntered

    private void lbS4MouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lbS4MouseExited
    {//GEN-HEADEREND:event_lbS4MouseExited
        lbS4.setOpaque(false);
    }//GEN-LAST:event_lbS4MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbP1;
    private javax.swing.JLabel lbP2;
    private javax.swing.JLabel lbP3;
    private javax.swing.JLabel lbP4;
    private javax.swing.JLabel lbP5;
    private javax.swing.JLabel lbProducto;
    private javax.swing.JLabel lbProveedor;
    private javax.swing.JLabel lbPrv1;
    private javax.swing.JLabel lbPrv2;
    private javax.swing.JLabel lbPrv3;
    private javax.swing.JLabel lbS1;
    private javax.swing.JLabel lbS2;
    private javax.swing.JLabel lbS3;
    private javax.swing.JLabel lbS4;
    private javax.swing.JLabel lbSuc;
    private javax.swing.JPanel pnProd;
    private javax.swing.JPanel pnProv;
    private javax.swing.JPanel pnRegistro;
    private javax.swing.JPanel pnRegistro1;
    private javax.swing.JPanel pnSuc;
    // End of variables declaration//GEN-END:variables
}
