/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import cjb.ci.CtrlInterfaz;
import cjb.ci.Validaciones;
import conexion.Crud;
import conexion.ManipulaSelecciones;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniel Yair Mendoza
 */
public class PnAgregarProv extends javax.swing.JPanel
{

    /**
     * Creates new form PnAgregarFarm
     */
    public PnAgregarProv()
    {
        initComponents();
        VtnPrincipal.disablePaste(cNombre, cClave, cDireccion, cCorreo);
        msj.setVisible(false);
    }

    public Icon icono(String direccion, int ancho, int alto)
    {
        Icon img = new ImageIcon(new ImageIcon(getClass().getResource(direccion)).getImage().getScaledInstance(ancho, alto, java.awt.Image.SCALE_SMOOTH));
        return img;
    }

    public static void validaAlfanumerico(KeyEvent ke, int len, String s)
    {
        if (s.length() == len)
        {
            ke.consume();
        } else
        {
            van(ke);
        }
    }

    private static void van(KeyEvent ke)
    {
        char c = ke.getKeyChar();
        if (!((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9')
                || c == '.' || c == ' ' || c == 'ñ' || c == 'Ñ' || c == 'á' || c == 'Á' || c == 'é'
                || c == 'É' || c == 'í' || c == 'Í' || c == 'ó' || c == 'Ó' || c == 'ú' || c == 'Ú'
                || c == '@' || c == '_' || c == '.'))
        {
            ke.setKeyChar((char) KeyEvent.VK_BACK_SPACE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        AgregarFarmacias = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cNombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        RegresarIN = new javax.swing.JPanel();
        RegresarINtxt = new javax.swing.JLabel();
        cClave = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        cDireccion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        cCorreo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        msj = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();

        AgregarFarmacias.setBackground(new java.awt.Color(255, 255, 255));
        AgregarFarmacias.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51)));
        AgregarFarmacias.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Agregar Proveedor");
        AgregarFarmacias.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 29, -1, 30));

        cNombre.setBorder(null);
        cNombre.setName("nombre"); // NOI18N
        cNombre.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                cNombreKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                cNombreKeyTyped(evt);
            }
        });
        AgregarFarmacias.add(cNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 340, 30));

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Nombre");
        AgregarFarmacias.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 100, 20));

        jSeparator9.setBackground(new java.awt.Color(0, 51, 51));
        AgregarFarmacias.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 340, 10));

        RegresarIN.setBackground(new java.awt.Color(255, 51, 51));

        RegresarINtxt.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        RegresarINtxt.setForeground(new java.awt.Color(255, 255, 255));
        RegresarINtxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RegresarINtxt.setText("Regresar");
        RegresarINtxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        RegresarINtxt.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                RegresarINtxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                RegresarINtxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                RegresarINtxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout RegresarINLayout = new javax.swing.GroupLayout(RegresarIN);
        RegresarIN.setLayout(RegresarINLayout);
        RegresarINLayout.setHorizontalGroup(
            RegresarINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegresarINLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(RegresarINtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        RegresarINLayout.setVerticalGroup(
            RegresarINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegresarINLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(RegresarINtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        AgregarFarmacias.add(RegresarIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 280, 170, 30));

        cClave.setBorder(null);
        cClave.setName("clave"); // NOI18N
        cClave.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cClaveActionPerformed(evt);
            }
        });
        cClave.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                cClaveKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                cClaveKeyTyped(evt);
            }
        });
        AgregarFarmacias.add(cClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 340, 30));

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("Clave");
        AgregarFarmacias.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 160, 20));

        jSeparator10.setBackground(new java.awt.Color(0, 51, 51));
        AgregarFarmacias.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 340, 10));

        cDireccion.setBorder(null);
        cDireccion.setName("direccion"); // NOI18N
        cDireccion.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                cDireccionKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                cDireccionKeyTyped(evt);
            }
        });
        AgregarFarmacias.add(cDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 340, 30));

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("Direccion");
        AgregarFarmacias.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 150, 20));

        jSeparator11.setBackground(new java.awt.Color(0, 51, 51));
        AgregarFarmacias.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 340, 10));

        cCorreo.setBorder(null);
        cCorreo.setName("correo"); // NOI18N
        cCorreo.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                cCorreoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                cCorreoKeyTyped(evt);
            }
        });
        AgregarFarmacias.add(cCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 340, 30));

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 102));
        jLabel9.setText("Correo");
        AgregarFarmacias.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 100, 20));

        jSeparator12.setBackground(new java.awt.Color(0, 51, 51));
        AgregarFarmacias.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 340, 10));

        msj.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        msj.setForeground(new java.awt.Color(35, 35, 35));
        msj.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        msj.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/advertencia.png"))); // NOI18N
        AgregarFarmacias.add(msj, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 320, 60));

        btnAgregar.setBackground(new java.awt.Color(66, 141, 141));
        btnAgregar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar proveedor");
        btnAgregar.setContentAreaFilled(false);
        btnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar.setOpaque(true);
        btnAgregar.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                btnAgregarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                btnAgregarFocusLost(evt);
            }
        });
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnAgregarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                btnAgregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                btnAgregarMouseExited(evt);
            }
        });
        btnAgregar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAgregarActionPerformed(evt);
            }
        });
        AgregarFarmacias.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 220, 170, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(AgregarFarmacias, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(AgregarFarmacias, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cNombreKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_cNombreKeyPressed
    {//GEN-HEADEREND:event_cNombreKeyPressed
        if (evt.getKeyChar() == '\n')
        {
            cClave.requestFocus();
        }
    }//GEN-LAST:event_cNombreKeyPressed

    private void cNombreKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_cNombreKeyTyped
    {//GEN-HEADEREND:event_cNombreKeyTyped
        Validaciones.validaAlfabeticos(evt, 20, cNombre.getText());
        if (evt.getKeyChar() == '.')
        {
            evt.setKeyChar((char) 8);
        }
    }//GEN-LAST:event_cNombreKeyTyped

    private void RegresarINtxtMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_RegresarINtxtMouseClicked
    {//GEN-HEADEREND:event_RegresarINtxtMouseClicked
        VtnPrincipal.mostrarPanel(new PnInicio(), jPanel1);
    }//GEN-LAST:event_RegresarINtxtMouseClicked

    private void RegresarINtxtMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_RegresarINtxtMouseEntered
    {//GEN-HEADEREND:event_RegresarINtxtMouseEntered
        RegresarIN.setBackground(new Color(204, 0, 0));
    }//GEN-LAST:event_RegresarINtxtMouseEntered

    private void RegresarINtxtMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_RegresarINtxtMouseExited
    {//GEN-HEADEREND:event_RegresarINtxtMouseExited
        RegresarIN.setBackground(new Color(255, 51, 51));
    }//GEN-LAST:event_RegresarINtxtMouseExited

    private void cClaveActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cClaveActionPerformed
    {//GEN-HEADEREND:event_cClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cClaveActionPerformed

    private void cClaveKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_cClaveKeyPressed
    {//GEN-HEADEREND:event_cClaveKeyPressed
        if (evt.getKeyChar() == '\n')
        {
            cDireccion.requestFocus();
        }
    }//GEN-LAST:event_cClaveKeyPressed

    private void cClaveKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_cClaveKeyTyped
    {//GEN-HEADEREND:event_cClaveKeyTyped
        Validaciones.validaEntero(evt, 5, cClave.getText());
    }//GEN-LAST:event_cClaveKeyTyped

    private void cDireccionKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_cDireccionKeyPressed
    {//GEN-HEADEREND:event_cDireccionKeyPressed
        if (evt.getKeyChar() == '\n')
        {
            cCorreo.requestFocus();
        }
    }//GEN-LAST:event_cDireccionKeyPressed

    private void cDireccionKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_cDireccionKeyTyped
    {//GEN-HEADEREND:event_cDireccionKeyTyped
        Validaciones.validaAlfabeticos(evt, 20, cDireccion.getText());
        if (evt.getKeyChar() == '.')
        {
            evt.setKeyChar((char) 8);
        }
    }//GEN-LAST:event_cDireccionKeyTyped

    private void cCorreoKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_cCorreoKeyPressed
    {//GEN-HEADEREND:event_cCorreoKeyPressed
        if (evt.getKeyChar() == '\n')
        {
            btnAgregar.requestFocus();
        }
    }//GEN-LAST:event_cCorreoKeyPressed

    private void cCorreoKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_cCorreoKeyTyped
    {//GEN-HEADEREND:event_cCorreoKeyTyped
        validaAlfanumerico(evt, 30, cCorreo.getText());
    }//GEN-LAST:event_cCorreoKeyTyped

    private void btnAgregarMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnAgregarMouseClicked
    {//GEN-HEADEREND:event_btnAgregarMouseClicked

    }//GEN-LAST:event_btnAgregarMouseClicked

    private void btnAgregarMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnAgregarMouseEntered
    {//GEN-HEADEREND:event_btnAgregarMouseEntered
        btnAgregar.setBackground(new java.awt.Color(31, 68, 68));
    }//GEN-LAST:event_btnAgregarMouseEntered

    private void btnAgregarMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnAgregarMouseExited
    {//GEN-HEADEREND:event_btnAgregarMouseExited
        btnAgregar.setBackground(new java.awt.Color(66, 141, 141));
    }//GEN-LAST:event_btnAgregarMouseExited

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAgregarActionPerformed
    {//GEN-HEADEREND:event_btnAgregarActionPerformed
        if (VtnPrincipal.vComponentes(cNombre, cClave, cDireccion, cCorreo))
        {
            msj.setVisible(true);
            msj.setText("<html>" + VtnPrincipal.componentes(cNombre, cClave, cDireccion, cCorreo) + "<html>");
        } else
        {
            if (VtnPrincipal.validaCad(cNombre.getText(), "^(?!\\s)(.*\\S)?(?!\\s)$"))
            {

                if (ManipulaSelecciones.validaCampo("SELECT p.nombreProv FROM proveedor p;", cNombre.getText()))
                {
                    if (ManipulaSelecciones.validaCampo("SELECT p.claveProv FROM proveedor p;", cClave.getText()))
                    {
                        Crud.insercion(
                                "INSERT INTO proveedor (nombreProv, claveProv, direccion, correo) VALUES ("
                                + "'" + cNombre.getText() + "'" + ", "
                                + "'" + cClave.getText() + "'" + ", "
                                + "'" + cDireccion.getText() + "'" + ", "
                                + "'" + cCorreo.getText() + "'"
                                + "); "
                        );
                        msj.setVisible(false);
                        CtrlInterfaz.limpia(cNombre, cClave, cDireccion, cCorreo);
                        JOptionPane.showMessageDialog(null, "Proveedor agregado con exito", "Altas", JOptionPane.PLAIN_MESSAGE, icono("/imagenes/comprobado.png", 50, 50));
                    } else
                    {
                        msj.setVisible(false);
                        JOptionPane.showMessageDialog(null, "Clave de proveedor ya existente", "Altas", JOptionPane.PLAIN_MESSAGE, icono("/imagenes/error.png", 50, 50));
                        CtrlInterfaz.selecciona(cClave);
                    }
                } else
                {
                    msj.setVisible(false);
                    JOptionPane.showMessageDialog(null, "Nombre de proveedor ya existente", "Altas", JOptionPane.PLAIN_MESSAGE, icono("/imagenes/error.png", 50, 50));
                    CtrlInterfaz.selecciona(cNombre);
                }

            } else
            {
                msj.setVisible(true);
                msj.setText("<html>" + "Nombre de farmacia no valido" + "<html>");
                CtrlInterfaz.selecciona(cNombre);
            }
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnAgregarFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_btnAgregarFocusGained
    {//GEN-HEADEREND:event_btnAgregarFocusGained
        btnAgregar.setBackground(new java.awt.Color(31, 68, 68));
    }//GEN-LAST:event_btnAgregarFocusGained

    private void btnAgregarFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_btnAgregarFocusLost
    {//GEN-HEADEREND:event_btnAgregarFocusLost
        btnAgregar.setBackground(new java.awt.Color(66, 141, 141));
    }//GEN-LAST:event_btnAgregarFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AgregarFarmacias;
    private javax.swing.JPanel RegresarIN;
    private javax.swing.JLabel RegresarINtxt;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JTextField cClave;
    private javax.swing.JTextField cCorreo;
    private javax.swing.JTextField cDireccion;
    private javax.swing.JTextField cNombre;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel msj;
    // End of variables declaration//GEN-END:variables
}
