/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import cjb.ci.CtrlInterfaz;
import cjb.ci.Validaciones;
import conexion.Crud;
import conexion.ManipulaSelecciones;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniel Yair Mendoza
 */
public class PnAgregarSuc extends javax.swing.JPanel
{

    String farm;

    /**
     * Creates new form PnAgregarSuc
     */
    public PnAgregarSuc()
    {
        initComponents();
        VtnPrincipal.disablePaste(cClaveS, cNombreS, cEstado);
        msj.setVisible(false);
        llenadoFarm(cmFarmaciaSuc);
    }

    public void llenadoFarm(JComboBox cb)
    {
        ArrayList<String> f = ManipulaSelecciones.select("SELECT * FROM farmacia f;");
        for (int i = 0; i < f.size(); i++)
        {
            cb.addItem(f.get(i));
        }
    }


    public Icon icono(String direccion, int ancho, int alto)
    {
        Icon img = new ImageIcon(new ImageIcon(getClass().getResource(direccion)).getImage().getScaledInstance(ancho, alto, java.awt.Image.SCALE_SMOOTH));
        return img;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        AgregarSucursales = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        cClaveS = new javax.swing.JTextField();
        jSeparator16 = new javax.swing.JSeparator();
        cNombreS = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jSeparator17 = new javax.swing.JSeparator();
        cEstado = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jSeparator18 = new javax.swing.JSeparator();
        jLabel28 = new javax.swing.JLabel();
        cmFarmaciaSuc = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        msj = new javax.swing.JLabel();
        RegresarIN = new javax.swing.JPanel();
        RegresarINtxt = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        cCiudad = new javax.swing.JTextField();
        jSeparator19 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        cTelefono = new javax.swing.JTextField();
        jSeparator20 = new javax.swing.JSeparator();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AgregarSucursales.setBackground(new java.awt.Color(255, 255, 255));
        AgregarSucursales.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51)));
        AgregarSucursales.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 102, 102));
        jLabel14.setText("Agregar Sucursal");
        AgregarSucursales.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, -1, 30));

        cClaveS.setBorder(null);
        cClaveS.setName("clave"); // NOI18N
        cClaveS.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                cClaveSKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                cClaveSKeyTyped(evt);
            }
        });
        AgregarSucursales.add(cClaveS, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 340, 30));

        jSeparator16.setBackground(new java.awt.Color(0, 51, 51));
        AgregarSucursales.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 340, 10));

        cNombreS.setBorder(null);
        cNombreS.setName("nombre"); // NOI18N
        cNombreS.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                cNombreSKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                cNombreSKeyTyped(evt);
            }
        });
        AgregarSucursales.add(cNombreS, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 340, 30));

        jLabel16.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 102, 102));
        jLabel16.setText("Nombre");
        AgregarSucursales.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 100, 20));

        jSeparator17.setBackground(new java.awt.Color(0, 51, 51));
        AgregarSucursales.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 340, 10));

        cEstado.setBorder(null);
        cEstado.setName("Estado"); // NOI18N
        cEstado.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cEstadoActionPerformed(evt);
            }
        });
        cEstado.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                cEstadoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                cEstadoKeyTyped(evt);
            }
        });
        AgregarSucursales.add(cEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 340, 30));

        jLabel17.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 102, 102));
        jLabel17.setText("Telefono");
        AgregarSucursales.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 150, 20));

        jSeparator18.setBackground(new java.awt.Color(0, 51, 51));
        AgregarSucursales.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, 340, 10));

        jLabel28.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 102, 102));
        jLabel28.setText("Clave de Sucursal");
        AgregarSucursales.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 150, 20));

        cmFarmaciaSuc.setBackground(new java.awt.Color(0, 102, 102));
        cmFarmaciaSuc.addPopupMenuListener(new javax.swing.event.PopupMenuListener()
        {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt)
            {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt)
            {
                cmFarmaciaSucPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt)
            {
            }
        });
        cmFarmaciaSuc.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cmFarmaciaSucActionPerformed(evt);
            }
        });
        cmFarmaciaSuc.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                cmFarmaciaSucKeyPressed(evt);
            }
        });
        AgregarSucursales.add(cmFarmaciaSuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 160, -1));

        jLabel29.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 102, 102));
        jLabel29.setText("Farmacia");
        AgregarSucursales.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 150, 20));

        btnAgregar.setBackground(new java.awt.Color(66, 141, 141));
        btnAgregar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar sucursal");
        btnAgregar.setContentAreaFilled(false);
        btnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar.setOpaque(true);
        btnAgregar.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                btnAgregarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                btnAgregarFocusLost(evt);
            }
        });
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnAgregarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                btnAgregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                btnAgregarMouseExited(evt);
            }
        });
        btnAgregar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAgregarActionPerformed(evt);
            }
        });
        AgregarSucursales.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 200, 170, 30));

        msj.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        msj.setForeground(new java.awt.Color(35, 35, 35));
        msj.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        msj.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/advertencia.png"))); // NOI18N
        AgregarSucursales.add(msj, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 370, 320, 60));

        RegresarIN.setBackground(new java.awt.Color(255, 51, 51));

        RegresarINtxt.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        RegresarINtxt.setForeground(new java.awt.Color(255, 255, 255));
        RegresarINtxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RegresarINtxt.setText("Regresar");
        RegresarINtxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        RegresarINtxt.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                RegresarINtxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                RegresarINtxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                RegresarINtxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout RegresarINLayout = new javax.swing.GroupLayout(RegresarIN);
        RegresarIN.setLayout(RegresarINLayout);
        RegresarINLayout.setHorizontalGroup(
            RegresarINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegresarINLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(RegresarINtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        RegresarINLayout.setVerticalGroup(
            RegresarINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegresarINLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(RegresarINtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        AgregarSucursales.add(RegresarIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, 170, 30));

        jLabel18.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 102, 102));
        jLabel18.setText("Estado");
        AgregarSucursales.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 150, 20));

        cCiudad.setBorder(null);
        cCiudad.setName("Ciudad"); // NOI18N
        cCiudad.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cCiudadActionPerformed(evt);
            }
        });
        cCiudad.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                cCiudadKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                cCiudadKeyTyped(evt);
            }
        });
        AgregarSucursales.add(cCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 340, 30));

        jSeparator19.setBackground(new java.awt.Color(0, 51, 51));
        AgregarSucursales.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 340, 10));

        jLabel19.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 102, 102));
        jLabel19.setText("Ciudad");
        AgregarSucursales.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 150, 20));

        cTelefono.setBorder(null);
        cTelefono.setName("Telefono"); // NOI18N
        cTelefono.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cTelefonoActionPerformed(evt);
            }
        });
        cTelefono.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                cTelefonoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                cTelefonoKeyTyped(evt);
            }
        });
        AgregarSucursales.add(cTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 340, 30));

        jSeparator20.setBackground(new java.awt.Color(0, 51, 51));
        AgregarSucursales.add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 340, 10));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(AgregarSucursales, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(AgregarSucursales, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void cClaveSKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_cClaveSKeyPressed
    {//GEN-HEADEREND:event_cClaveSKeyPressed
        if (evt.getKeyChar() == '\n')
        {
            cNombreS.requestFocus();
        }
    }//GEN-LAST:event_cClaveSKeyPressed

    private void cClaveSKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_cClaveSKeyTyped
    {//GEN-HEADEREND:event_cClaveSKeyTyped
        Validaciones.validaEntero(evt, 5, cClaveS.getText());
    }//GEN-LAST:event_cClaveSKeyTyped

    private void cNombreSKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_cNombreSKeyPressed
    {//GEN-HEADEREND:event_cNombreSKeyPressed
        if (evt.getKeyChar() == '\n')
        {
            cEstado.requestFocus();
        }
    }//GEN-LAST:event_cNombreSKeyPressed

    private void cNombreSKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_cNombreSKeyTyped
    {//GEN-HEADEREND:event_cNombreSKeyTyped
        Validaciones.validaAlfabeticos(evt, 20, cNombreS.getText());
        if (evt.getKeyChar() == '.')
        {
            evt.setKeyChar((char) 8);
        }
    }//GEN-LAST:event_cNombreSKeyTyped

    private void cEstadoKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_cEstadoKeyTyped
    {//GEN-HEADEREND:event_cEstadoKeyTyped
        Validaciones.validaAlfabeticos(evt, 20, cEstado.getText());
        if (evt.getKeyChar() == '.')
        {
            evt.setKeyChar((char) 8);
        }
    }//GEN-LAST:event_cEstadoKeyTyped

    private void cmFarmaciaSucPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt)//GEN-FIRST:event_cmFarmaciaSucPopupMenuWillBecomeInvisible
    {//GEN-HEADEREND:event_cmFarmaciaSucPopupMenuWillBecomeInvisible

    }//GEN-LAST:event_cmFarmaciaSucPopupMenuWillBecomeInvisible

    private void cmFarmaciaSucActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cmFarmaciaSucActionPerformed
    {//GEN-HEADEREND:event_cmFarmaciaSucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmFarmaciaSucActionPerformed

    private void btnAgregarFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_btnAgregarFocusGained
    {//GEN-HEADEREND:event_btnAgregarFocusGained
        btnAgregar.setBackground(new java.awt.Color(31, 68, 68));
    }//GEN-LAST:event_btnAgregarFocusGained

    private void btnAgregarFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_btnAgregarFocusLost
    {//GEN-HEADEREND:event_btnAgregarFocusLost
        btnAgregar.setBackground(new java.awt.Color(66, 141, 141));
    }//GEN-LAST:event_btnAgregarFocusLost

    private void btnAgregarMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnAgregarMouseClicked
    {//GEN-HEADEREND:event_btnAgregarMouseClicked

    }//GEN-LAST:event_btnAgregarMouseClicked

    private void btnAgregarMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnAgregarMouseEntered
    {//GEN-HEADEREND:event_btnAgregarMouseEntered
        btnAgregar.setBackground(new java.awt.Color(31, 68, 68));
    }//GEN-LAST:event_btnAgregarMouseEntered

    private void btnAgregarMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnAgregarMouseExited
    {//GEN-HEADEREND:event_btnAgregarMouseExited
        btnAgregar.setBackground(new java.awt.Color(66, 141, 141));
    }//GEN-LAST:event_btnAgregarMouseExited

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAgregarActionPerformed
    {//GEN-HEADEREND:event_btnAgregarActionPerformed
        if (VtnPrincipal.vComponentes(cClaveS, cNombreS, cEstado, cCiudad, cTelefono))
        {
            msj.setVisible(true);
            msj.setText("<html>" + VtnPrincipal.componentes(cClaveS, cNombreS, cEstado, cCiudad, cTelefono) + "<html>");
        } else
        {
            if (VtnPrincipal.validaCad(cNombreS.getText(), "^(?!\\s)(.*\\S)?(?!\\s)$"))
            {

                if (ManipulaSelecciones.validaCampo("SELECT s.nombreSuc FROM  sucursal s;", cNombreS.getText()))
                {
                    if (ManipulaSelecciones.validaCampo("SELECT s.claveSuc FROM  sucursal s;", cClaveS.getText()))
                    {
                        Crud.insercion(
                                "INSERT INTO sucursal (nombreSuc, nombreFarm, claveSuc, estado, ciudad, telefono) VALUES ("
                                + "'" + cNombreS.getText() + "'" + ", "
                                + "'" + String.valueOf(cmFarmaciaSuc.getSelectedItem()) + "'" + ", "
                                + "'" + cClaveS.getText() + "'" + ", "
                                + "'" + cEstado.getText() + "'" + ", "
                                + "'" + cCiudad.getText() + "'" + ", "
                                + cTelefono.getText()
                                + "); "
                        );
                        msj.setVisible(false);
                        CtrlInterfaz.limpia(cClaveS, cNombreS, cEstado, cCiudad, cTelefono);
                        JOptionPane.showMessageDialog(null, "Sucursal agregada con exito", "Altas", JOptionPane.PLAIN_MESSAGE, icono("/imagenes/comprobado.png", 50, 50));
                    } else
                    {
                        msj.setVisible(false);
                        JOptionPane.showMessageDialog(null, "Clave de sucursal ya existente", "Altas", JOptionPane.PLAIN_MESSAGE, icono("/imagenes/error.png", 50, 50));
                        CtrlInterfaz.selecciona(cClaveS);
                    }

                } else
                {
                    msj.setVisible(false);
                    JOptionPane.showMessageDialog(null, "Nombre de sucursal ya existente", "Altas", JOptionPane.PLAIN_MESSAGE, icono("/imagenes/error.png", 50, 50));
                    CtrlInterfaz.selecciona(cNombreS);
                }

            } else
            {
                msj.setVisible(true);
                msj.setText("<html>" + "Nombre de sucursal no valido" + "<html>");
                CtrlInterfaz.selecciona(cNombreS);
            }
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void RegresarINtxtMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_RegresarINtxtMouseClicked
    {//GEN-HEADEREND:event_RegresarINtxtMouseClicked
        VtnPrincipal.mostrarPanel(new PnInicio(), jPanel1);
    }//GEN-LAST:event_RegresarINtxtMouseClicked

    private void RegresarINtxtMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_RegresarINtxtMouseEntered
    {//GEN-HEADEREND:event_RegresarINtxtMouseEntered
        RegresarIN.setBackground(new Color(204, 0, 0));
    }//GEN-LAST:event_RegresarINtxtMouseEntered

    private void RegresarINtxtMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_RegresarINtxtMouseExited
    {//GEN-HEADEREND:event_RegresarINtxtMouseExited
        RegresarIN.setBackground(new Color(255, 51, 51));
    }//GEN-LAST:event_RegresarINtxtMouseExited

    private void cEstadoKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_cEstadoKeyPressed
    {//GEN-HEADEREND:event_cEstadoKeyPressed
        if (evt.getKeyChar() == '\n')
        {
            cCiudad.requestFocus();
        }
    }//GEN-LAST:event_cEstadoKeyPressed

    private void cmFarmaciaSucKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_cmFarmaciaSucKeyPressed
    {//GEN-HEADEREND:event_cmFarmaciaSucKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_UP || evt.getKeyCode() == KeyEvent.VK_DOWN || evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            evt.consume();
        }
    }//GEN-LAST:event_cmFarmaciaSucKeyPressed

    private void cEstadoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cEstadoActionPerformed
    {//GEN-HEADEREND:event_cEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cEstadoActionPerformed

    private void cCiudadActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cCiudadActionPerformed
    {//GEN-HEADEREND:event_cCiudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cCiudadActionPerformed

    private void cCiudadKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_cCiudadKeyPressed
    {//GEN-HEADEREND:event_cCiudadKeyPressed
        if (evt.getKeyChar() == '\n')
        {
            cTelefono.requestFocus();
        }
    }//GEN-LAST:event_cCiudadKeyPressed

    private void cCiudadKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_cCiudadKeyTyped
    {//GEN-HEADEREND:event_cCiudadKeyTyped
        Validaciones.validaAlfabeticos(evt, 20, cCiudad.getText());
        if (evt.getKeyChar() == '.')
        {
            evt.setKeyChar((char) 8);
        }
    }//GEN-LAST:event_cCiudadKeyTyped

    private void cTelefonoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cTelefonoActionPerformed
    {//GEN-HEADEREND:event_cTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cTelefonoActionPerformed

    private void cTelefonoKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_cTelefonoKeyPressed
    {//GEN-HEADEREND:event_cTelefonoKeyPressed
        if (evt.getKeyChar() == '\n')
        {
            btnAgregar.requestFocus();
        }
    }//GEN-LAST:event_cTelefonoKeyPressed

    private void cTelefonoKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_cTelefonoKeyTyped
    {//GEN-HEADEREND:event_cTelefonoKeyTyped
        Validaciones.validaEntero(evt, 10, cTelefono.getText());
    }//GEN-LAST:event_cTelefonoKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AgregarSucursales;
    private javax.swing.JPanel RegresarIN;
    private javax.swing.JLabel RegresarINtxt;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JTextField cCiudad;
    private javax.swing.JTextField cClaveS;
    private javax.swing.JTextField cEstado;
    private javax.swing.JTextField cNombreS;
    private javax.swing.JTextField cTelefono;
    private javax.swing.JComboBox<String> cmFarmaciaSuc;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JLabel msj;
    // End of variables declaration//GEN-END:variables
}
