/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import conexion.Crud;
import conexion.ManipulaSelecciones;
import static frames.VtnPrincipal.Submenus;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.text.html.parser.DTDConstants;

/**
 *
 * @author Daniel Yair Mendoza
 */
public class PnBajaFarmacia extends javax.swing.JPanel
{

    /**
     * Creates new form PnConsFarm
     */
    public PnBajaFarmacia()
    {
        initComponents();
        llenadoCombo(cmFarm, "SELECT * FROM farmacia f;");
    }

    public void llenadoCombo(JComboBox cb, String consulta)
    {
        ArrayList<String> f = ManipulaSelecciones.select(consulta);
        for (int i = 0; i < f.size(); i++)
        {
            cb.addItem(f.get(i));
        }
    }

    public Icon icono(String direccion, int ancho, int alto)
    {
        Icon img = new ImageIcon(new ImageIcon(getClass().getResource(direccion)).getImage().getScaledInstance(ancho, alto, java.awt.Image.SCALE_SMOOTH));
        return img;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbProd = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        cmFarm = new javax.swing.JComboBox<>();
        btnBusc = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbProd.setFont(new java.awt.Font("Tahoma", 0, 31)); // NOI18N
        lbProd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbProd.setText("Baja Farmacia");
        jPanel2.add(lbProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 220, 40));

        jLabel34.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 102, 102));
        jLabel34.setText("Farmacia:");
        jPanel2.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 100, 20));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 460, 20));

        cmFarm.setBackground(new java.awt.Color(0, 102, 102));
        cmFarm.addPopupMenuListener(new javax.swing.event.PopupMenuListener()
        {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt)
            {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt)
            {
                cmFarmPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt)
            {
            }
        });
        cmFarm.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cmFarmActionPerformed(evt);
            }
        });
        cmFarm.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                cmFarmKeyPressed(evt);
            }
        });
        jPanel2.add(cmFarm, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 160, -1));

        btnBusc.setBackground(new java.awt.Color(66, 141, 141));
        btnBusc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBusc.setForeground(new java.awt.Color(255, 255, 255));
        btnBusc.setText("Eliminar");
        btnBusc.setContentAreaFilled(false);
        btnBusc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBusc.setOpaque(true);
        btnBusc.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnBuscMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                btnBuscMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                btnBuscMouseExited(evt);
            }
        });
        btnBusc.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnBuscActionPerformed(evt);
            }
        });
        jPanel2.add(btnBusc, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 110, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 510));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 510));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnBuscActionPerformed
    {//GEN-HEADEREND:event_btnBuscActionPerformed
        Crud.elimina("DELETE p FROM producto AS p JOIN sucursal AS s ON s.nombreSuc = p.nombreSuc"
                + " JOIN farmacia AS f ON f.nombreFarm = s.nombreFarm  WHERE f.nombreFarm = '" + String.valueOf(cmFarm.getSelectedItem()) + "';");
        Crud.elimina("DELETE FROM sucursal WHERE nombreFarm = '" + String.valueOf(cmFarm.getSelectedItem()) + "';");
        Crud.elimina("DELETE FROM farmacia WHERE nombreFarm = '" + String.valueOf(cmFarm.getSelectedItem()) + "';");
        cmFarm.removeAllItems();
        llenadoCombo(cmFarm, "SELECT f.nombreFarm FROM farmacia f ORDER BY f.nombreFarm;");
        JOptionPane.showMessageDialog(null, "Farmacia eliminada con exito", "Altas", JOptionPane.PLAIN_MESSAGE, icono("/imagenes/comprobado.png", 50, 50));
        if (!ManipulaSelecciones.validaSuc("SELECT f.nombreFarm FROM farmacia f ORDER BY f.nombreFarm;"))
        {
            JOptionPane.showMessageDialog(null, "Has eliminado todas las Farmacias con sus datos relacionados \n Da de alta nuevas sucursales", "Altas", JOptionPane.PLAIN_MESSAGE, icono("/imagenes/comprobado.png", 50, 50));
            VtnPrincipal.mostrarPanelN(new PnInicio(), jPanel1);
            VtnPrincipal.mostrarPanel2(new PnSubAltas(), Submenus);
        }
    }//GEN-LAST:event_btnBuscActionPerformed

    private void btnBuscMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnBuscMouseEntered
    {//GEN-HEADEREND:event_btnBuscMouseEntered
        btnBusc.setBackground(new java.awt.Color(31, 68, 68));
    }//GEN-LAST:event_btnBuscMouseEntered

    private void btnBuscMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnBuscMouseExited
    {//GEN-HEADEREND:event_btnBuscMouseExited
        btnBusc.setBackground(new java.awt.Color(66, 141, 141));
    }//GEN-LAST:event_btnBuscMouseExited

    private void btnBuscMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnBuscMouseClicked
    {//GEN-HEADEREND:event_btnBuscMouseClicked

    }//GEN-LAST:event_btnBuscMouseClicked

    private void cmFarmPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt)//GEN-FIRST:event_cmFarmPopupMenuWillBecomeInvisible
    {//GEN-HEADEREND:event_cmFarmPopupMenuWillBecomeInvisible

    }//GEN-LAST:event_cmFarmPopupMenuWillBecomeInvisible

    private void cmFarmActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cmFarmActionPerformed
    {//GEN-HEADEREND:event_cmFarmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmFarmActionPerformed

    private void cmFarmKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_cmFarmKeyPressed
    {//GEN-HEADEREND:event_cmFarmKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_UP || evt.getKeyCode() == KeyEvent.VK_DOWN || evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            evt.consume();
        }
    }//GEN-LAST:event_cmFarmKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBusc;
    private javax.swing.JComboBox<String> cmFarm;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbProd;
    // End of variables declaration//GEN-END:variables
}
