/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import clases.Farmacia;
import clases.Producto;
import clases.Sucursal;
import conexion.ManipulaSelecciones;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Daniel Yair Mendoza
 */
public class PnConsProd extends javax.swing.JPanel
{

    int ancho = 0;

    /**
     * Creates new form PnConsFarm
     */
    public PnConsProd()
    {
        initComponents();
        msj.setVisible(false);
        llenadoTabla(ManipulaSelecciones.llenaProd("SELECT * FROM producto s ORDER BY s.claveProd;"));
    }

    public void llenadoTabla(ArrayList<Producto> arr)
    {
        if (arr.isEmpty())
        {
            msj.setVisible(true);
        } else
        {
            for (int i = 0; i < arr.size(); i++)
            {
                pnTabla.add(generador(arr.get(i).getClave(), arr.get(i).getNombrePrd(), arr.get(i).getNombreSuc(), arr.get(i).getNombreProv(), String.valueOf(arr.get(i).getPrecio()),
                        String.valueOf(arr.get(i).getExistencia())),
                        new org.netbeans.lib.awtextra.AbsoluteConstraints(0, ancho, 880, 32));
                ancho += 32;
                pnTabla.updateUI();
            }
        }
    }

    public JPanel generador(String clave, String nomP, String nomSuc, String nomProv, String precio, String existencia)
    {
        JPanel pnRegistro1 = new javax.swing.JPanel();
        JLabel jLabel20 = new javax.swing.JLabel();
        JLabel jLabel21 = new javax.swing.JLabel();
        JLabel jLabel22 = new javax.swing.JLabel();
        JLabel jLabel23 = new javax.swing.JLabel();
        JLabel jLabel24 = new javax.swing.JLabel();
        JLabel jLabel25 = new javax.swing.JLabel();
        pnRegistro1.setBackground(new java.awt.Color(255, 255, 255));
        pnRegistro1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnRegistro1.setBackground(new java.awt.Color(255, 255, 255));
        pnRegistro1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText(clave);
        jLabel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnRegistro1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 32));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel21.setText(nomP);
        jLabel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnRegistro1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 200, 32));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel22.setText(nomSuc);
        jLabel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnRegistro1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 200, 32));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel23.setText(nomProv);
        jLabel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnRegistro1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 200, 32));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText(precio);
        jLabel24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnRegistro1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 120, 32));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText(existencia);
        jLabel25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnRegistro1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, 80, 32));
        return pnRegistro1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnTabla = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        msj = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(66, 141, 141));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Clave");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("nombre");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 200, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Precio");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 120, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Existencia");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, 80, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Proveedor");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 200, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Sucursal");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 200, 30));

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 880, 30));

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        pnTabla.setBackground(new java.awt.Color(255, 255, 255));
        pnTabla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jScrollPane1.setViewportView(pnTabla);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 880, 320));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 31)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Productos");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 230, 30));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 460, 20));

        msj.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        msj.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        msj.setText("No se encontraron productos");
        add(msj, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 420, 30));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel msj;
    private javax.swing.JPanel pnTabla;
    // End of variables declaration//GEN-END:variables
}
