/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import clases.Farmacia;
import conexion.ManipulaSelecciones;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Daniel Yair Mendoza
 */
public class PnConsProveedor extends javax.swing.JPanel
{

    int ancho = 0;

    /**
     * Creates new form PnConsFarm
     */
    public PnConsProveedor()
    {
        initComponents();
        msj.setVisible(false);
        llenadoTabla(ManipulaSelecciones.llenaFarm("SELECT * FROM proveedor p ORDER BY p.nombreProv;"));
    }

    public void llenadoTabla(ArrayList<Farmacia> arr)
    {

        if (arr.isEmpty())
        {
            msj.setVisible(false);
        } else
        {
            for (int i = 0; i < arr.size(); i++)
            {
                pnTabla.add(generador(arr.get(i).getNombre(), arr.get(i).getClaveFarmacia(), arr.get(i).getTipoSociedad(), arr.get(i).getRfc()),
                        new org.netbeans.lib.awtextra.AbsoluteConstraints(0, ancho, 720, -1));
                ancho += 32;
                pnTabla.updateUI();
            }
        }
    }

    public JPanel generador(String nombre, String clave, String tipo, String rfc)
    {
        JPanel pnDatos = new JPanel();
        pnDatos.setBackground(new java.awt.Color(255, 255, 255));
        pnDatos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnDatos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPanel pnNombre = new JPanel();
        pnNombre.setBackground(new java.awt.Color(255, 255, 255));
        pnNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnNombre.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLabel lblNom = new JLabel();
        lblNom.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lblNom.setText(nombre);// NOI18N
        lblNom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnNombre.add(lblNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 30));

        pnDatos.add(pnNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 32));

        JPanel pnClave = new JPanel();
        pnClave.setBackground(new java.awt.Color(255, 255, 255));
        pnClave.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnClave.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLabel lblClave = new JLabel();
        lblClave.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lblClave.setText(clave);// NOI18N
        lblClave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnClave.add(lblClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 30));

        pnDatos.add(pnClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 180, 32));

        JPanel pnTipo = new JPanel();
        pnTipo.setBackground(new java.awt.Color(255, 255, 255));
        pnTipo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnTipo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLabel lblTipo = new JLabel();
        lblTipo.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lblTipo.setText(tipo);// NOI18N
        lblTipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnTipo.add(lblTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 30));

        pnDatos.add(pnTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 180, 32));

        JPanel pnRFC = new JPanel();
        pnRFC.setBackground(new java.awt.Color(255, 255, 255));
        pnRFC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnRFC.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLabel lblRFC = new JLabel();
        lblRFC.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lblRFC.setText(rfc);// NOI18N
        lblRFC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnRFC.add(lblRFC, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 30));

        pnDatos.add(pnRFC, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 180, 32));
        return pnDatos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnTabla = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        msj = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(66, 141, 141));
        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Nombre");
        jPanel4.add(jLabel3);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Clave");
        jPanel4.add(jLabel4);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("direccion");
        jPanel4.add(jLabel5);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("correo");
        jPanel4.add(jLabel2);

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 720, 30));

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        pnTabla.setBackground(new java.awt.Color(255, 255, 255));
        pnTabla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jScrollPane1.setViewportView(pnTabla);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 720, 320));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 31)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Proveedores");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 230, 30));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 460, 10));

        msj.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        msj.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        msj.setText("No se encontraron proveedores");
        add(msj, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 420, 30));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel msj;
    private javax.swing.JPanel pnTabla;
    // End of variables declaration//GEN-END:variables
}
