/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import java.awt.Color;

/**
 *
 * @author Daniel Yair Mendoza
 */
public class PnSubMod extends javax.swing.JPanel
{

    /**
     * Creates new form PnSubAltas
     */
    public PnSubMod()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        SubmenuTraspasos = new javax.swing.JPanel();
        modFarm = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        modSuc = new javax.swing.JLabel();
        modProd = new javax.swing.JLabel();
        modProv = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1000, 70));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SubmenuTraspasos.setBackground(new java.awt.Color(0, 102, 102));
        SubmenuTraspasos.setForeground(new java.awt.Color(0, 102, 102));
        SubmenuTraspasos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        modFarm.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        modFarm.setForeground(new java.awt.Color(255, 255, 255));
        modFarm.setText("Mod. Farmacia");
        modFarm.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        modFarm.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                modFarmMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                modFarmMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                modFarmMouseExited(evt);
            }
        });
        SubmenuTraspasos.add(modFarm, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, 30));

        jLabel32.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("Modifica");
        SubmenuTraspasos.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 20, 200, -1));

        modSuc.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        modSuc.setForeground(new java.awt.Color(255, 255, 255));
        modSuc.setText("Mod. Sucursal");
        modSuc.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        modSuc.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                modSucMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                modSucMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                modSucMouseExited(evt);
            }
        });
        SubmenuTraspasos.add(modSuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 100, 30));

        modProd.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        modProd.setForeground(new java.awt.Color(255, 255, 255));
        modProd.setText("Mod. Producto");
        modProd.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        modProd.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                modProdMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                modProdMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                modProdMouseExited(evt);
            }
        });
        SubmenuTraspasos.add(modProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 100, 30));

        modProv.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        modProv.setForeground(new java.awt.Color(255, 255, 255));
        modProv.setText("Mod. Proveedor");
        modProv.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        modProv.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                modProvMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                modProvMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                modProvMouseExited(evt);
            }
        });
        SubmenuTraspasos.add(modProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 120, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SubmenuTraspasos, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SubmenuTraspasos, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void modFarmMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_modFarmMouseClicked
    {//GEN-HEADEREND:event_modFarmMouseClicked
        VtnPrincipal.mostrarPanel(new PnModFarm(), VtnPrincipal.PnPrincipal);
    }//GEN-LAST:event_modFarmMouseClicked

    private void modFarmMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_modFarmMouseEntered
    {//GEN-HEADEREND:event_modFarmMouseEntered
        modFarm.setBackground(new Color(0, 51, 51));
    }//GEN-LAST:event_modFarmMouseEntered

    private void modFarmMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_modFarmMouseExited
    {//GEN-HEADEREND:event_modFarmMouseExited
        modFarm.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_modFarmMouseExited

    private void modSucMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_modSucMouseClicked
    {//GEN-HEADEREND:event_modSucMouseClicked
        VtnPrincipal.mostrarPanel(new PnModSuc(), VtnPrincipal.PnPrincipal);
    }//GEN-LAST:event_modSucMouseClicked

    private void modSucMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_modSucMouseEntered
    {//GEN-HEADEREND:event_modSucMouseEntered
        modSuc.setBackground(new Color(0, 51, 51));
    }//GEN-LAST:event_modSucMouseEntered

    private void modSucMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_modSucMouseExited
    {//GEN-HEADEREND:event_modSucMouseExited
        modSuc.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_modSucMouseExited

    private void modProdMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_modProdMouseClicked
    {//GEN-HEADEREND:event_modProdMouseClicked
        VtnPrincipal.mostrarPanel(new PnModProd(), VtnPrincipal.PnPrincipal);
    }//GEN-LAST:event_modProdMouseClicked

    private void modProdMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_modProdMouseEntered
    {//GEN-HEADEREND:event_modProdMouseEntered
        modProd.setBackground(new Color(0, 51, 51));
    }//GEN-LAST:event_modProdMouseEntered

    private void modProdMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_modProdMouseExited
    {//GEN-HEADEREND:event_modProdMouseExited
        modProd.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_modProdMouseExited

    private void modProvMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_modProvMouseClicked
    {//GEN-HEADEREND:event_modProvMouseClicked
        VtnPrincipal.mostrarPanel(new PnModProv(), VtnPrincipal.PnPrincipal);
    }//GEN-LAST:event_modProvMouseClicked

    private void modProvMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_modProvMouseEntered
    {//GEN-HEADEREND:event_modProvMouseEntered
        modProv.setBackground(new Color(0, 51, 51));
    }//GEN-LAST:event_modProvMouseEntered

    private void modProvMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_modProvMouseExited
    {//GEN-HEADEREND:event_modProvMouseExited
        modProv.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_modProvMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SubmenuTraspasos;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel modFarm;
    private javax.swing.JLabel modProd;
    private javax.swing.JLabel modProv;
    private javax.swing.JLabel modSuc;
    // End of variables declaration//GEN-END:variables
}
