/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import java.awt.Color;

/**
 *
 * @author Daniel Yair Mendoza
 */
public class PnSubBajas extends javax.swing.JPanel
{

    /**
     * Creates new form PnSubAltas
     */
    public PnSubBajas()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        SubmenuTraspasos = new javax.swing.JPanel();
        bajaFarm = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        bajaSuc = new javax.swing.JLabel();
        bajaProd = new javax.swing.JLabel();
        bajaProv = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1000, 70));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SubmenuTraspasos.setBackground(new java.awt.Color(0, 102, 102));
        SubmenuTraspasos.setForeground(new java.awt.Color(0, 102, 102));
        SubmenuTraspasos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bajaFarm.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        bajaFarm.setForeground(new java.awt.Color(255, 255, 255));
        bajaFarm.setText("Baja Farmacia");
        bajaFarm.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bajaFarm.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                bajaFarmMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                bajaFarmMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                bajaFarmMouseExited(evt);
            }
        });
        SubmenuTraspasos.add(bajaFarm, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, 30));

        jLabel32.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("Bajas");
        SubmenuTraspasos.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 20, 200, -1));

        bajaSuc.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        bajaSuc.setForeground(new java.awt.Color(255, 255, 255));
        bajaSuc.setText("Baja Sucursal");
        bajaSuc.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bajaSuc.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                bajaSucMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                bajaSucMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                bajaSucMouseExited(evt);
            }
        });
        SubmenuTraspasos.add(bajaSuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 100, 30));

        bajaProd.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        bajaProd.setForeground(new java.awt.Color(255, 255, 255));
        bajaProd.setText("Baja Producto");
        bajaProd.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bajaProd.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                bajaProdMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                bajaProdMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                bajaProdMouseExited(evt);
            }
        });
        SubmenuTraspasos.add(bajaProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 100, 30));

        bajaProv.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        bajaProv.setForeground(new java.awt.Color(255, 255, 255));
        bajaProv.setText("Baja Proveedor");
        bajaProv.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bajaProv.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                bajaProvMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                bajaProvMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                bajaProvMouseExited(evt);
            }
        });
        SubmenuTraspasos.add(bajaProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 100, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SubmenuTraspasos, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SubmenuTraspasos, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void bajaFarmMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_bajaFarmMouseClicked
    {//GEN-HEADEREND:event_bajaFarmMouseClicked
        VtnPrincipal.mostrarPanel(new PnBajaFarmacia(), VtnPrincipal.PnPrincipal);
    }//GEN-LAST:event_bajaFarmMouseClicked

    private void bajaFarmMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_bajaFarmMouseEntered
    {//GEN-HEADEREND:event_bajaFarmMouseEntered
        bajaFarm.setBackground(new Color(0, 51, 51));
    }//GEN-LAST:event_bajaFarmMouseEntered

    private void bajaFarmMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_bajaFarmMouseExited
    {//GEN-HEADEREND:event_bajaFarmMouseExited
        bajaFarm.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_bajaFarmMouseExited

    private void bajaSucMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_bajaSucMouseClicked
    {//GEN-HEADEREND:event_bajaSucMouseClicked
        VtnPrincipal.mostrarPanel(new PnBajaSuc(), VtnPrincipal.PnPrincipal);
    }//GEN-LAST:event_bajaSucMouseClicked

    private void bajaSucMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_bajaSucMouseEntered
    {//GEN-HEADEREND:event_bajaSucMouseEntered
        bajaSuc.setBackground(new Color(0, 51, 51));
    }//GEN-LAST:event_bajaSucMouseEntered

    private void bajaSucMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_bajaSucMouseExited
    {//GEN-HEADEREND:event_bajaSucMouseExited
        bajaSuc.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_bajaSucMouseExited

    private void bajaProdMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_bajaProdMouseClicked
    {//GEN-HEADEREND:event_bajaProdMouseClicked
        VtnPrincipal.mostrarPanel(new PnBajaProd(), VtnPrincipal.PnPrincipal);
    }//GEN-LAST:event_bajaProdMouseClicked

    private void bajaProdMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_bajaProdMouseEntered
    {//GEN-HEADEREND:event_bajaProdMouseEntered
        bajaProd.setBackground(new Color(0, 51, 51));
    }//GEN-LAST:event_bajaProdMouseEntered

    private void bajaProdMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_bajaProdMouseExited
    {//GEN-HEADEREND:event_bajaProdMouseExited
        bajaProd.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_bajaProdMouseExited

    private void bajaProvMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_bajaProvMouseClicked
    {//GEN-HEADEREND:event_bajaProvMouseClicked
        VtnPrincipal.mostrarPanel(new PnBajaProv(), VtnPrincipal.PnPrincipal);
    }//GEN-LAST:event_bajaProvMouseClicked

    private void bajaProvMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_bajaProvMouseEntered
    {//GEN-HEADEREND:event_bajaProvMouseEntered
        bajaProv.setBackground(new Color(0, 51, 51));
    }//GEN-LAST:event_bajaProvMouseEntered

    private void bajaProvMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_bajaProvMouseExited
    {//GEN-HEADEREND:event_bajaProvMouseExited
        bajaProv.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_bajaProvMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SubmenuTraspasos;
    private javax.swing.JLabel bajaFarm;
    private javax.swing.JLabel bajaProd;
    private javax.swing.JLabel bajaProv;
    private javax.swing.JLabel bajaSuc;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
